language: java

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "PBoy3g9vP57O/TfMSSv1n8xM5rzdGvPFJlxeyHNuFLhGDNrWi/iYK0DluXNvjtM95VSjXfe13wn0vQKn4jiUFawxa1UV72XpDg5x8wT/bSNfNoY3XtY8izT5Yi6MF24MzYjdhxc79D06kFXWXQdkcD/sTma9zCP7et5e9+RMWJQvIC1h+pXGVDpxaQV2VVR8qHgeg7YzOhVJemX1mdujBL5vRfYPh4ubxGEazt110C6voRyWN1jAgwcZgH+0CaGFrySR9C49q6e1sevfR0dMzMMV3JeT18R7pB4vdriQ1IyUvJrQSj4lb+4UT0vcPfdKUJXlga+k5wM3ARzhBP3G23MFbwbw14KYnkGYwNJa0Hc3Yh1r0RYPWdUQLrsvQzmJ5IPv+5AX625/ZRMlbvasyO22eekBZxm6UiRUyOoihqAM00/d68JDRHEO07oYkK3F9NsC21Rb587IkAUio04/UiQInVnmJNAQpdqApnQsk1juQcGAepHR1B7ii65BD04cECF+Em6noERQfg//yT5nOESMkwMu1BCW0eWOk52WeL7q4OnvOM8+YVQy9cYMTcAz/+ZF1WUCHi6DoxLeF7zTj/RnILsFXAip1ccbOI+7klF1LIPLrcAjlDBUZIunV5Edq1LqZQfrDGSaonnQMQrId5y5o2cJo5BvOo1ZGHDiX7U="
    - secure: "lxY3vuULwK8BWwMJtPAzKqzpOb8+WEtO8kVcx0kyrpvl3l0Wk4I6uqnoFNP+47DffglYlroxX9Ajqd8G28ZXfXfg3Zy+xRwrraxztzKOPiJXHU5/PY2UTzW9VJXFNw5ROoatYQUPYyFHaWgC4+88rjM8E+Y5J6MLElLsqDaLnRMwfYEqRHICkTLVJ8RIfRY4+gmRuiIGI4C3kxmbcw01zTH0tSn2IkAfCqbtmbNC6+19CCqJxFA4eYnvy/BfpX2XGNO6dIH9TI2gMxJJGiV69OinNOxGpmJxnOLBCB6HpJHz2H6a0NvlLaxbfEOxgfl8I/QDxbz09NM/AP0FW28RrSKKHNsbDu+G5R/hkDH8ObstPZjgXlbO8c7Khn1gJwrBEkKNG1OWZzmKMswEuchbquZ6EoGt6Jsv+FE+8B9OMOE6+DZhbGhErxFiOLoKRI1CF++EBDZxfWg3U/CuElGFCyDsvQD3zcUvbQ//vXWqy7wYmTrue4La5rN4qVurnIlt9xwBBIAkEYF4wFdgglGIacUPrSPtrDl5FOzovc1JiGjPnCk8u6j9G9ebpojrQWP1F1ioINkb1QJ/zt1i0Gq/AH1Nmvm/KCn4FahNMQiXWfeKDhX007onrbfYKYNEEul3ujm1azqyHxKfqMr4QQ03bGTlRBZWI9F2JESzy3tKA8Q="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
